### ISSUE TITLE
Deleting a page in Sudan dashboard 

### ISSUE THREAD

**Issue by FatmaGiha** [WorldHealthOrganization/herams-backend#121]
I created Page for Infrastructure and functionality and a new page for condition. I tried to delete the old page for condition (currently placed after the Overview page), but didn't know how. 
Please advise how to delete pages of the dashboards

**Comment by FatmaGiha** [comment]
My question is related to Sudan Project Dashboards

**Comment by SamMousa** [comment]
This should now work on the staging environment; the delete button will only show up if the page has no elements.

**Comment by FatmaGiha** [comment]
I have just tested the condition page on Sudan's project on the staging environment (created a new page for condition, added a map as an element, and deleted this element). The page has no element but still, I can't delete it as the Delete button is not showing on the page!

**Comment by SamMousa** [comment]
Can you try again?

**Comment by FatmaGiha** [comment]
I did the testing again, and it worked on the staging environment, but the delete button still not showing on the production environment page, where I want to delete the "Condition" page

**Comment by FatmaGiha** [comment]
Yes, it works now
